apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar-log-example
  namespace: default
  labels:
    app: sidecar-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar-log
  template:
    metadata:
      labels:
        app: sidecar-log
    spec:
      containers:
        - name: sc-loggen
          image: busybox
          command: ["/bin/sh"]
          args: ["-c", "while true; do date >> /var/log/app.log; sleep 1; done"]
          volumeMounts:
            - name: log-volume
              mountPath: /var/log
        - name: sc-logread
          image: busybox
          command: ["/bin/sh"]
          args: ["-c","tail -f /var/log/app.log"]
          volumeMounts:
            - name: log-volume
              mountPath: var/log
      volumes:
        - name: log-volume
          emptyDir: {}
