apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.js: |
    window.APP_CONFIG = {
      gatewayPath: '/eazybank',
      keycloakUrl: '/realms/master/protocol/openid-connect/token',
      clientId: 'eazybank-callcenter-cc',
      clientSecret: '4VuZ7QiUhcN7SUHr9Vz2bq3bGUKeWIuQ',
      tokenRefreshInterval: 50000,
      services: {
        accounts: { port: 8080 },
        loans:    { port: 8090 },
        cards:    { port: 9000 },
        gateway:  { port: 8072 },
        keycloak: { port: 80   }
      }
    };
