apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    events { worker_connections 1024; }
    http {
      include /etc/nginx/mime.types;
      server {
        listen 80;
        root /usr/share/nginx/html;
        index eazybank.html;

        location / {
          try_files $uri $uri/ /eazybank.html;
        }

        location /config.js {
          root /etc/nginx/conf.d;
          add_header Content-Type application/javascript;
        }

        location /eazybank/ {
          proxy_pass http://gatewayserver:8072;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_connect_timeout 30s;
          proxy_read_timeout 120s;
          proxy_send_timeout 120s;
        }

        location /realms/ {
          proxy_pass http://keycloak:80;
          proxy_http_version 1.1;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_connect_timeout 30s;
          proxy_read_timeout 120s;
          proxy_send_timeout 120s;
        }
      }
    }
