# ── ACCOUNTS DB ──
apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountsdb
  template:
    metadata:
      labels:
        app: accountsdb
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: accountsdb
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_PASSWORD
          value: root
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: accountsdb
spec:
  type: NodePort
  selector:
    app: accountsdb
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 31120
---
# ── LOANS DB ──
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loansdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loansdb
  template:
    metadata:
      labels:
        app: loansdb
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: loansdb
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_PASSWORD
          value: root
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: loansdb
spec:
  type: NodePort
  selector:
    app: loansdb
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 31121
---
# ── CARDS DB ──
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardsdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cardsdb
  template:
    metadata:
      labels:
        app: cardsdb
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: cardsdb
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_PASSWORD
          value: root
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: cardsdb
spec:
  type: NodePort
  selector:
    app: cardsdb
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 31122
